# Generated by Django 2.2.2 on 2019-06-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=10)),
                ('joindate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
